In [1]:
import pandas as pd

In [2]:
covidData = pd.read_excel("database/dados-preprocessados.xlsx")

In [3]:
covidData

,CS_SEXO,NU_IDADE_N,CS_RACA,SURTO_SG,FEBRE,TOSSE,GARGANTA,DISPNEIA,DESC_RESP,SATURACAO,...,PNEUMOPATI,IMUNODEPRE,RENAL,OBESIDADE,UTI,SUPORT_VEN,DT_INTERNA,DT_EVOLUCA,CLASSI_FIN,EVOLUCAO
0,0,ADULTO3,4,2,1,1,1,1,1,1,...,2,2,2,2,1,2,2020-03-20,11/04/2020,5,1
1,1,IDOSO1,4,2,1,1,1,1,1,1,...,2,2,2,2,2,2,2020-03-23,28/03/2020,5,1
2,1,ADULTO3,4,2,1,1,2,1,1,1,...,2,2,2,2,2,1,2020-04-05,07/04/2020,5,2
3,1,ADULTO3,4,2,1,1,2,1,1,1,...,2,2,2,2,1,1,2020-03-25,08/04/2020,5,2
4,1,IDOSO1,4,2,1,1,2,1,1,1,...,2,2,2,2,2,2,2020-03-25,31/03/2020,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,1,ADULTO2,4,1,1,9,9,9,9,1,...,2,2,2,2,1,1,2020-08-21,01/09/2020,5,2
705,1,ADULTO3,4,2,9,9,9,1,1,1,...,2,2,2,2,2,2,2020-05-26,26/07/2020,5,2
706,0,IDOSO2,4,2,1,9,9,1,9,1,...,2,2,2,2,2,2,NaT,27/06/2020,5,2
707,0,IDOSO3,1,9,1,1,2,1,1,9,...,2,2,1,2,2,9,NaT,15/05/2020,5,2
708,1,ADULTO3,4,2,2,1,1,1,1,1,...,2,2,2,2,1,2,NaT,02/09/2020,5,2

In [24]:
data_internacao = covidData['DT_INTERNA']

In [26]:
data_internacao_formatado = data_internacao

In [14]:
# data_saida.isnull().sum()
# data_internacao.isnull().sum()

24

In [30]:
for i in data_internacao.count()N:
    data_internacao_formatado[i] = data_internacao[i].strftime('%d/%m/%Y')

TypeError: 'numpy.int32' object is not iterable

In [ ]:
data_internacao